---
shared:
  image: buildpack-deps
  # image: rockylinux:8.7

jobs:
  main:
    requires: [~pr, ~commit]
    # Steps definition block.
    steps:
      # - presd-setup-scm: yum install git -y
      - export: export GREETING="Hello, world!"
      - hello: echo $GREETING
      - collenction_teigi: export SD_COLLECTION="/aaa/release/1.0.0 , /bbb/release/1.*.0, /ccc/release/1.0.*, /ddd/release/1.*.*, /aaa/test/3.0.0"
      - pip_install: |
          wget https://bootstrap.pypa.io/get-pip.py
          python3 get-pip.py
          pip3 install requests
      - sdcmdtest: sd-cmd exec foo/bar@latest # install_collection.pyを実行している
      - sdcmdtest2: sd-cmd exec foo/bar2@latest # install_collection2.pyを実行している
      - sdcmdtest3: |
          install_ver=`sd-cmd exec foo/bar3@latest 1.*.0`# install_collection3.pyを実行している
          echo $install_ver
      # - sdcmdtest: foo/bar@latest
      # - set-metadata: meta set example.coverage 99.95
  # second_job:
  #   requires: [main] # second_job will run after main job is done
  #   steps:
  #     - make_target: make greetings
  #     - get-metadata: meta get example
  #     - run_arbitrary_script: ./my_script.sh